---
- hosts: devserver
  become: yes
  ignore_errors: yes
  vars:
    username: danie
    pkg_name: httpd
  tasks:
  - name: Creating user
    user:
      name: "{{ username }}"
      comment: danie admin
      shell: /bin/bash
        #when: ansible_os_family == "RedHat"
  - name: create file
    file:
      path: /tmp/ansible.txt
      state: touch
      mode: '0600'
    register: output
  - name: read the output
    debug: 
     msg: "hello from ansible this is running on {{ansible_os_family}}"
  - name: Create directory
    file:   
      path: /tmp/dir
      state: directory
      mode: '0777'
    tags:
     - c1
     - app1
  - name: create a file
    shell: cat /etc/passwd | grep serge
  - name: install apache
    yum:
      name: "{{ pkg_name }}"
      state: present

  - name: install finger and wget
    package:
      name: "{{ item }}"
      state: present 
      with_items:
        - wget
        - finger
         
